### ISSUE TITLE
Same strings need to be config var

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/plugin-emojis#2]
Same strings here need to be config var to easy translate

https://github.com/kiwiirc/plugin-emojis/blob/13cc431ab4fecbfa49e2d9673d4ca69587f8c6d1/plugin.js#L72

And can be more :
<picker set="emojione" :native="useNative()" :style="{ position: 'absolute', 
zIndex: 10, bottom: '60px', right: '20px' }" title="Scegli la tua emoji…" emoji="point_up"  :i18n="{ search: 'Cerca', categories: { search: 'Risultati della ricerca', recent: 'Recenti' } }" @select="onEmojiSelected" />

**Comment by srmcgann** [comment]
Done.
